### ISSUE TITLE
Build fails with latest nodeJS version (10.0.0)

### ISSUE THREAD

**Issue by mtf90** [LearnLib/alex#9]
After upgrading the nodeJS version to 10.0.0, building the frontend of ALEX fails with following error message:

```
[INFO] --- exec-maven-plugin:1.4.0:exec (npm-build) @ alex-frontend ---

> ALEX@1.5.0-SNAPSHOT build /home/frohme/workspace/alex/frontend/src/main/javascript
> grunt

Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v4.5.3

Running "concat:libs" (concat) task

Running "uglify:libs" (uglify) task
>> 1 file created 2.16 MB → 611.87 kB

Running "browserify:dist" (browserify) task
Warning: Cannot find module 'browserify-ngannotate' from '/home/frohme/workspace/alex/frontend/src/main/javascript' Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! ALEX@1.5.0-SNAPSHOT build: `grunt`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the ALEX@1.5.0-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mtf90** [comment]
Thanks for the quick reply and fix. Works like a charm
